~*
~*  This job builds the CHESS 4.9 game. It copies the program library
~*  from the chess49 tape, applies the local modifications in
~*  chess49.mods, assembles and links the program, generates the
~*  CHESS49 user library and the CHESDOC documentation file (the same
~*  steps as the BUILD procedure on the tape, plus the modset), edits
~*  the CHESS startup procedure into the PRODUCT file, and adds
~*  directives to the DIRFILE file specifying that PROC/CHESS should be
~*  inserted into the deadstart file library number associated with
~*  other games.
~*
CHESS49.
$USER,INSTALL,${../site.cfg:PASSWORDS:INSTALL:INSTALL}.
$NORERUN.
$SETTL,*.
$SETASL,*.
$SETJSL,*.
$COPYBR,INPUT,DIR.
$COPYBR,INPUT,PROC.
$COPYBR,INPUT,MODS.
$ASSIGN,${2},TAPE,D=GE,LB=KL,F=I,PO=R.
$REWIND,TAPE.
$SKIPF,TAPE.
$COPY,TAPE,OPL.
$RETURN,TAPE.
$REWIND,OPL,MODS.
$MODIFY,LO=E,F,I=MODS.
$COMPASS,I,B=CHESTXT,L=0,S=0.
$COMPASS,I,L=0,G=CHESTXT.
$LOAD,LGO.
$NOGO,ABS.
$LIBGEN,F=ABS,P=CHESS49.
$LIBRARY,CHESS49/A.
$NOTE,IN./EXPLAIN,ALL/END
CHESS,IN,CHESDOC,LIBRARY.
$REPLACE,CHESS49,CHESDOC.
$ATTACH,PRODUCT,DIRFILE/M=W,WB.
$LIBEDIT,P=PRODUCT,B=PROC,I=0,C.
$LIBEDIT,P=DIRFILE,B=DIR,I=0,C.
***
*** CHESS49 COMPLETE
***
EXIT.
***
*** CHESS49 FAILED
***
~eor
CHESS
*ADD LIB${1},PROC/CHESS
~eor
~include chess.proc
~eor
~include chess49.mods
