⍝ Workspace FILESYS from library *APL1 on NOS 2.8.7 (APL2.1.014 97/11/06)
⍝ Listed with )LOAD *APL1 FILESYS and ∇name[⎕]∇ under APL,TT=713; $xx mnemonics converted to glyphs.

⍝ )LOAD *APL1 FILESYS:
⍝   FILESYS 84/02/21 12:16:39

⍝ )FNS:
⍝   CFPOS   CFREAD  CFWRITE CLIST   CMAP    CSUBMIT DESCRIBE        FCLEAR  FCOPY   FCREATE FERASE  FFREE   FIHOW   FMAP
⍝   FNAMES  FNUMS   FPACK   FPOS    FRDEL   FREAD   FRETURN FSTATUS FTIE    FUNTIE  FWRITE  PACKNAM PSTATUS PACKNAMHOW
⍝   SOURCE

⍝ )VARS:
⍝   ABSTRACT        GRPCONV GRPDOC  GRPPRIM

⍝ )GRPS:
⍝   GRPCONV GRPDOC  GRPPRIM

⍝ GRPDOC:
⍝   SOURCE
⍝   DESCRIBE
⍝   ABSTRACT
⍝   PACKNAMHOW

⍝ GRPPRIM:
⍝   FCREATE
⍝   FWRITE
⍝   FREAD
⍝   FERASE
⍝   FRDEL
⍝   FSTATUS
⍝   FNAMES
⍝   FNUMS
⍝   FUNTIE
⍝   FTIE
⍝   FPOS
⍝   CFWRITE
⍝   CFREAD
⍝   CFPOS
⍝   PSTATUS
⍝   FRETURN
⍝   FFREE
⍝   CSUBMIT
⍝   FPACK
⍝   PACKNAM

⍝ ABSTRACT:
⍝   MORE COMPLEX FUNCTIONS FOR FILE ACCESS AND CONTROL

      ∇CLIST B;K;L
[1]    →(0=0\0⍴K←B)/L1 ⍝ IF FILE ALREADY TIED
[2]    B FTIE K←1+⌈/0,FNUMS
[3]   L1:L←CFREAD K
[4]    →(0=⍴⍴L)/L2 ⍝ SCALAR INDICATES SPECIAL MARK
[5]    L
[6]    →L1
[7]   L2:→L3+2×L-1
[8]   L3:'-END OF RECORD-'
[9]    →L1
[10]   '-END OF FILE-'
[11]   →L1
[12]   '-END OF INFORMATION-'
[13]   FUNTIE(0≠0\0⍴B)/K
      ∇

      ∇CMAP B;K;P;C
[1]    →(0=0\0⍴K←B)/L1 ⍝ IF B IS NUMERIC
[2]    B FTIE K←1+⌈/0,FNUMS
[3]   L1:C←0
[4]   L2:→(0=⍴⍴P←CFREAD K)/L3
[5]    C←C+1
[6]    →L2
[7]   L3:→(C=0)/L4
[8]    C;' LINE',(C≠1)/'S'
[9]   L4:'EO','RFI'[P]
[10]   →(P<3)/L1
[11]   FUNTIE(0≠0\0⍴B)/K
      ∇

      ∇DESCRIBE
[1]    ''
[2]    'THIS WORKSPACE CONTAINS BASIC FUNCTIONS NEEDED TO USE THE'
[3]    'APL FILE SYSTEM, AND ADDITIONAL FUNCTIONS FOR MORE ELABORATE'
[4]    'FILE OPERATIONS.'
[5]    '       THIS WORKSPACE ALSO CONTAINS VARIATIONS  OF THE TWO'
[6]    'SAMPLE FUNCTIONS FCOPY AND CLIST SHOWN IN THE APL2.1 REFERENCE'
[7]    'MANUAL.  ALL DOCUMENTATION CAN BE FOUND IN SECTION 10 OF THE'
[8]    'APL2.1 REFERENCE MANUAL.'
[9]    ''
[10]   'GROUPS DEFINED'
[11]   ''
[12]   'GRPPRIM - ALL PRIMITIVE FUNCTIONS FROM FILESYS WORKSPACE.'
[13]   ''
[14]   'GRPCONV - THE ADDITIONAL CONVENIENCE FUNCTIONS IN THIS WORKSPACE.'
[15]   ''
[16]   'GRPDOC - THE DOCUMENTATION FUNCTIONS IN THIS WORKSPACE.'
[17]   ''
[18]   'PLEASE EITHER COPY GRPPRIM INTO THE WORKSPACE IN WHICH THE'
[19]   'FILE SYSTEM WILL BE USED, OR LOAD THIS WORKSPACE AND '
[20]   '        )ERASE .GRPDOC'
[21]   'TO AVOID USING STORAGE SPACE FOR THE DOCUMENTATION.'
      ∇

      ∇FCLEAR B;K
[1]    B←(FNUMS∈B)/FNUMS
[2]    K←(B ⎕FI 6)[;⎕IO+7]
[3]    ((~K)/B)⎕FI 4
[4]    (K/B)⎕FI 9
      ∇

      ∇A FCOPY B;P;K;I;J
[1]    A FTIE I←1+⌈/0,FNUMS
[2]    B FCREATE J←I+1
[3]    K←(FSTATUS I)[1]⍝ GET LARGEST RECORD NUMBER
[4]   L1:→(K<0)/L3
[5]    P←FREAD I,K ⍝ READ RECORD K FROM FILE I
[6]    →(FSTATUS I)[9]/L2 ⍝ IF ABSENT RECORD
[7]    P FWRITE J,K ⍝ WRITE RECORD K TO FILE J
[8]   L2:K←K-1
[9]    →L1
[10]  L3:FUNTIE I,J ⍝ UNTIE BOTH FILES
[11]   'COPY COMPLETE'
      ∇

      ∇FIHOW
[1]    'THE LOCKED FILE FUNCTIONS ARE LISTED HERE FOR THOSE'
[2]    'WHO WANT TO USE THE ⎕FI PRIMITIVE FORM.'
[3]    '(THIS IS A DUPLICATE OF PAGE 10-4, APL2.1 REFERENCE MANUAL)'
[4]    ''
[5]    'FUNCTION              PRIMITIVE FORM'
[6]    ''
[7]    'A FPACK B                A ⎕FI 0,B'
[8]    'A FCREATE B              A ⎕FI 1,B'
[9]    'A FWRITE B               A ⎕FI 2,B'
[10]   'Z←FREAD B                Z←⎕FI 3,B'
[11]   'FERASE B                 B ⎕FI 4'
[12]   'FRDEL B                    ⎕FI 5,B'
[13]   'A←FSTATUS B             Z←B ⎕FI 6'
[14]   'Z←FNAMES                Z←⎕FI 7'
[15]   'Z←FNUMS                  Z←⎕FI 8'
[16]   'FUNTIE B                 B ⎕FI 9'
[17]   'A FTIE B                 A ⎕FI 10,B'
[18]   'FPOS B                     ⎕FI 11,B'
[19]   'A CFWRITE B              A ⎕FI 12,B'
[20]   'A←CFREAD B               Z←⎕FI 13,B'
[21]   'A CFPOS B                  ⎕FI 14,B,A'
[22]   'Z←CSUBMIT B              Z←⎕FI 15,B'
[23]   'Z←FFREE B                Z←⎕FI 16,B'
[24]   →
      ∇

      ∇FMAP B;K;P
[1]    →(0=0\0⍴K←B)/L1 ⍝ IF B IS NUMERIC
[2]    B FTIE K←1+⌈/0,FNUMS
[3]   L1:→(¯1≠1↑FSTATUS K)/L2 ⍝ IF FILE NOT EMPTY
[4]    'NO RECORDS'
[5]    →0
[6]   L2:'NUMBER, TYPE, DIMENSIONS'
[7]   L3:→(</2↑FSTATUS K)/L5 ⍝ IF FINISHED
[8]    P←FREAD K
[9]    →(FSTATUS K)[9]/L4 ⍝ IF READ FAILED
[10]   ¯1+(FSTATUS K)[2];0 1 0\'CN'[1+0=0\0⍴P];⍴P
[11]   →L3
[12]  L4:¯1+(FSTATUS K)[2];' ABSENT'
[13]   →L3
[14]  L5:FUNTIE(0≠0\0⍴B)/K
      ∇

      ∇FRETURN B;K
[1]    B←(K∈B)/K←⎕FI 8
[2]    K←(B ⎕FI 6)[;⎕IO+7]
[3]    ((~K)/B)⎕FI 4
[4]    (K/B)⎕FI 9
      ∇

      ∇PSTATUS;⎕IO;B;I;K;F;N;W
[1]    ⎕IO←1
[2]    B←⎕FI 8
[3]    →(0≠⍴B)/L0
[4]    'NO FILES TIED'
[5]    →0
[6]   L0:I←⎕FI 7
[7]    K←B,B ⎕FI 6
[8]    'NAME             NUMBER LAST R    POS    SIZE  UNUSED    LOST   TAILS'
[9]    F←7 0 7 0 7 0 8 0 8 0 8 0 8 0⍕((⍴B),7)↑K
[10]   K←K[;8 9 10]
[11]   N←1
[12]  L1:W←K[N;2]/' DA, '
[13]   →K[N;1]/L2
[14]   I[N;],F[N;],¯2↓W,K[N;3]/' READ FAILED  '
[15]   →L3
[16]  L2:I[N;],(7↑F[N;]),¯2↓'   CODED FILE, ',W
[17]  L3:→((⍴B)≥N←N+1)/L1
      ∇

      ∇PACKNAMHOW
[1]    'THE PACKNAM FUNCTION ALLOWS YOU TO SET THE DEFAULT AUXILIARY'
[2]    'PACK AND DEVICE TYPE FOR SUBSEQUENT PERMANENT FILE REFERENCES.'
[3]    'IT CALLS THE *PACKNAM* RA+1 REQUEST. FOR EXAMPLE:'
[4]    '      PACKNAM ''ABC    DL2'''
[5]    'SETS THE DEFAULT TO PACK ABC RESIDING ON DEVICE TYPE DL WITH'
[6]    'TWO SPINDLES.(NOTE THAT ALL BLANKS ARE CONVERTED TO 00 FOR'
[7]    'THE RA+1 CALL AND THAT THE DEVICE TYPE AND UNIT'
[8]    'MUST BE THE 8TH, 9TH, AND 10TH CHARACTERS.)'
[9]    'IF THE ARGUMENT IS THE EMPTY CHARACTER VECTOR, THEN'
[10]   'THE AUXILIARY DEVICE NAME IS CLEARED AND FURTHER PERMANENT'
[11]   'FILE REQUESTS REVERT TO THE STANDARD SYSTEM DEVICE.'
[12]   'YOU SHOULD CONSULT THE NOS 2 REFERENCE MANUAL, VOL 4,'
[13]   'FOR COMPLETE DETAILS.'
      ∇

      ∇SOURCE
[1]    ''
[2]    'ADDED MAY 12, 1975'
[3]    ''
[4]    'CLARK WIEDMANN'
[5]    'U.C.C.'
[6]    'G.R.C.'
[7]    'UNIV. OF MASS.'
[8]    'AMHERST, MA 01003'
[9]    ''
      ∇

⍝ )OFF:
⍝   UN=GUEST    LOG OFF  14.15.52. 
⍝   JSN=AADI     SRU-S=      1.252 
⍝   CHARACTERS=    8.426KCHS
⍝   IAF     CONNECT TIME 00.02.01.
⍝   LOGGED OUT.

⍝ Locked functions (12: DEFN ERROR on display): CFPOS CFREAD CFWRITE CSUBMIT FCREATE FERASE FFREE FNAMES FNUMS FPACK FPOS FRDEL FREAD FSTATUS FTIE FUNTIE FWRITE PACKNAM
